[server]
maxUploadSize = 15
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0ea5a4"
backgroundColor = "#f2fbfa"
secondaryBackgroundColor = "#dff3f1"
textColor = "#12324a"
font = "sans serif"
